
USE PropertyHubDB;

CREATE TABLE IF NOT EXISTS `Alquileres` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`usuario` VARCHAR(255) UNIQUE NOT NULL,
`password` VARCHAR(255),
`mail` VARCHAR(255) UNIQUE NOT NULL


); ENGINE = InnoDB;
